# From which image you want to start building your image
FROM nginx:latest

# For copying data from one directory to container
# ADD directory/where/data/is/present /directory/in/which/data/is/to/be/copied
ADD . /usr/share/ngnix/html